kind: pipeline
type: docker
name: default

trigger:
  branch:
    - master
  event:
    - tag

steps:
  - name: build-and-push
    image: plugins/docker
    settings:
      username: gitlab-ci-token
      password:
        from_secret: gitlab_token
      repo: registry.gitlab.com/${GITLAB_USERNAME}/hugo-go
      tags: ${DRONE_TAG}
      registry: registry.gitlab.com
    environment:
      GITLAB_USERNAME:
        from_secret: gitlab_username
