kind: pipeline
type: docker
name: default

trigger:
  branch:
    - master
  event:
    - tag

environment:
  GITLAB_USER:
    from_secret: gitlab_user

steps:
  - name: build-and-push
    image: plugins/docker
    settings:
      username: gitlab-ci-token
      password:
        from_secret: gitlab_token
      repo: registry.gitlab.com/${GITLAB_USER}/hugo-go
      tags: ${DRONE_TAG}
      registry: registry.gitlab.com